### ISSUE TITLE
A few comments about the first blog post

### ISSUE THREAD

**Issue by dscho** [prertik/prertik.github.io#1]
Hi @prertik! It is awesome that you blog about your journey, really cool.

Re: sending patches: my awesome colleague @derrickstolee recently had a similar problem, and started documenting in a more hands-on way what one needs to do. He did it in the form of https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md. Granted, some parts really only apply to Git for Windows, but a few (such as the "testing changes") may be useful in general.

Also, "begineer" -> "beginner" ;-)

**Comment by prertik** [comment]
Thanks, @dscho. I'm sorry I forgot to cc you on the mailing list. I'll update the blog post in a few hours.

**Comment by dscho** [comment]
@prertik I think you *did* Cc: me ;-)

**Comment by prertik** [comment]
Huh, how could that be? Because I remembered later that I had only Cc two mentors.
![screen shot 2018-05-02 at 3 36 10 pm](https://user-images.githubusercontent.com/12194950/39517149-bd8896b8-4e1e-11e8-84cd-3fa6a276ea81.png)

**Comment by prertik** [comment]
But, it's a good thing you got notified. :-)

**Comment by prertik** [comment]
Looks, like this, will be on hold for a day or two. The machine(Linux) I used to make the blog is in the shop for maintenance. My current machine macOS is running into some problems running hugo and the theme. I will see if I can fix this on mac.

**Comment by dscho** [comment]
Looks great!
